replicaCount: 2

image:
  repository: timur5050/k8sfastapiservice
  tag: latest

service:
  port: 8000
  type: LoadBalancer
  targetPort: 8000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

myEnvVar: "value"

strategy:
  maxSurge: 1
  maxUnavailable: 1

affinity:
  podAffinity:
      topologyKey: "kubernetes.io/hostname"



