"""users model

Revision ID: 34b4ff1cbc6c
Revises: 
Create Date: 2024-09-27 11:09:36.720997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b4ff1cbc6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('success_requests_count', sa.Integer(), nullable=True),
    sa.Column('failed_requests_count', sa.Integer(), nullable=True),
    sa.Column('total_success_requests_count', sa.Float(), nullable=True),
    sa.Column('total_failed_requests_count', sa.Float(), nullable=True),
    sa.Column('rate_limited_requests_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
